import os.path
Import(['env'])

files = [ Glob('*.c') + Glob('*.S') ]
subdirs = []

env.libc_objects += files

SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])
