import os.path
Import(['env'])

files = Glob('*.c')
subdirs = []

SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])

# 
files = [env.multiboot] + files + [
#env.oskit_clientos,
#env.oskit_kern,
#env.oskit_lmm,
#env.oskit_c,
#env.oskit_posix,
#env.oskit_com,
]

linkline = ' -Llib --start-group -loskit_c -loskit_clientos -loskit_kern -loskit_lmm --end-group'

hello = env.Program('hello',
 files, 
 #LIBPATH='#lib',
 LIBS=[
#	'oskit_c',
#	'oskit_clientos',
#	'oskit_kern',
#	'oskit_lmm',

	#'oskit_com',
	#'oskit_posix'
	],
 LINKFLAGS = env['LINKFLAGS'] + ' -T'+os.path.join(Dir('..').srcnode().path, 'src/link.ld') + linkline
)

Depends(hello, '#lib/liboskit_c.a')
Depends(hello, '#lib/liboskit_clientos.a')
Depends(hello, '#lib/liboskit_kern.a')
Depends(hello, '#lib/liboskit_lmm.a')

env.Command('#/kernel', hello, Copy("$TARGET", "$SOURCE"))
