/* This file is automatically generated.  Do not edit. */
/* FLASK */

typedef struct
{
    oskit_security_class_t tclass;
    char **common_pts;
    oskit_access_vector_t common_base;
} av_inherit_t;

static av_inherit_t av_inherit[] = {
   { OSKIT_SECCLASS_DIR, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_LNK_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_CHR_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_BLK_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_SOCK_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_FIFO_FILE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_PIPE, common_file_perm_to_string, 0x00010000UL },
   { OSKIT_SECCLASS_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_TCP_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_UDP_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_RAWIP_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_NETLINK_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_PACKET_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_UNIX_STREAM_SOCKET, common_socket_perm_to_string, 0x00080000UL },
   { OSKIT_SECCLASS_UNIX_DGRAM_SOCKET, common_socket_perm_to_string, 0x00080000UL },
};

#define AV_INHERIT_SIZE (sizeof(av_inherit)/sizeof(av_inherit_t))


/* FLASK */
