/* This file is automatically generated.  Do not edit. */
/*
 * Security object class definitions
 */
static char *class_to_string[] =
{
    "null",
    "security",
    "process",
    "system",
    "filesystem",
    "file",
    "dir",
    "fd",
    "lnk_file",
    "chr_file",
    "blk_file",
    "sock_file",
    "fifo_file",
    "pipe",
    "socket",
    "tcp_socket",
    "udp_socket",
    "rawip_socket",
    "node",
    "netif",
    "netlink_socket",
    "packet_socket",
    "unix_stream_socket",
    "unix_dgram_socket",
    "subject",
    "avc",
    "memory",
};

