/* This file is automatically generated.  Do not edit. */
/* FLASK */

static char *common_file_perm_to_string[] =
{
    "read",
    "write",
    "create",
    "getattr",
    "setattr",
    "lock",
    "relabelfrom",
    "relabelto",
    "transition",
    "append",
    "access",
    "unlink",
    "link",
    "rename",
    "execute",
    "pathconf",
};

static char *common_socket_perm_to_string[] =
{
    "read",
    "write",
    "create",
    "getattr",
    "setattr",
    "lock",
    "relabelfrom",
    "relabelto",
    "transition",
    "bind",
    "connect",
    "getopt",
    "setopt",
    "shutdown",
    "recvfrom",
    "sendto",
    "recv_msg",
    "send_msg",
    "name_bind",
};


/* FLASK */
