/* This file is automatically generated.  Do not edit. */
static char *initial_sid_to_string[] =
{
    "null",
    "kernel",
    "security",
    "unlabeled",
    "fs",
    "file",
    "file_labels",
    "init",
    "proc",
    "any_socket",
    "port",
    "netif",
    "netmsg",
    "node",
    "icmp_socket",
    "tcp_socket",
};

