import os.path
Import(['env'])

files = Glob('*.c') + Glob('*.cc')
subdirs = []

env.kern_objects = []

SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])

env.razor_kern = env.StaticLibrary('razor_kern', files)

#env.Command('#lib/${SOURCE}', razor_kern, Copy("$TARGET", "$SOURCE"))

#env.razor_objects += razor_kern
