import os.path
Import(['env'])

files = Glob('*.c')
subdirs = []

env.libc_objects = [ files ]

SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])

env.razor_c = env.StaticLibrary('razor_c', env.libc_objects)

#env.Command('#lib/${SOURCE}', razor_c, Copy("$TARGET", "$SOURCE"))

#env.razor_objects += razor_c
