import os.path
Import(['env'])

env.multiboot = env.Object('multiboot.S')

#env.multiboot = env.StaticLibrary('multiboot.S')

env.Command('#lib/${SOURCE}', env.multiboot, Copy("$TARGET", "$SOURCE"))
