import os.path
Import(['env'])

subdirs = [
'crt', 'kern', 'lmm',
'clientos', 'libc',
'posix',
'com',
'dev',
'diskpart',
'fsnamespace',
'memdebug',
'linux'
]

Mkdir("#lib")

SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])
