import os.path
Import(['env'])

subdirs = ['crt', 'kern', 'libc']

files = []

env.kernel_objects += [env.Object(i) for i in files]
SConscript([os.path.join(i, 'SConscript') for i in subdirs], exports = ['env'])
