import os.path
Import(['env'])

env.posix_objects = Glob('*.c')

env.oskit_posix = env.StaticLibrary('oskit_posix', env.posix_objects)

env.Command('#lib/${SOURCE}', env.oskit_posix, Copy("$TARGET", "$SOURCE"))
